import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import App from "./App";
import { Toaster } from "react-hot-toast";
//import { store } from "@/redux/store";

import {
  ClerkProvider
  
} from '@clerk/nextjs'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      
      <ClerkProvider>
       <App> 
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
            {children}
          
            <Toaster position="bottom-center" reverseOrder={false}/>
          
        </body>
      </html>
      </App>
      </ClerkProvider> 
       

  )
}



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AuthProvider>
//           <App>{children}</App>
//         </AuthProvider>
//         <Toaster position="bottom-center" reverseOrder={false}/>
//       </body>
//     </html>
//   );
// }
